name: 'Atlantis'

on: pull_request

permissions:
  contents: read

jobs:
  atlantis:
    name: 'Atlantis'
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
      atlantis:
        image: ghcr.io/runatlantis/atlantis:v0.23.2
        env:
          ATLANTIS_LOG_LEVEL: debug
          ATLANTIS_LOCKING_DB_TYPE: redis
          ATLANTIS_REDIS_HOST: localhost
          ATLANTIS_REPO_CONFIG: atlantis_repo.yml

    steps:
      # Pass event to Atlantis
      - name: Send event
        run: "curl -X POST -H 'Content-Type: application/json' --data '${{ github.event }}' http://localhost:6379/events"
      # Sleep
      - name: Sleep
        run: sleep 10