name: 'Atlantis'

on: pull_request

permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write
  statuses: write

jobs:
  atlantis:
    name: 'Atlantis'
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
      atlantis:
        image: ghcr.io/runatlantis/atlantis:v0.23.2
        ports:
          - 4141:4141
        env:
          ATLANTIS_DATA_DIR: /atlantis-data
          ATLANTIS_GH_USER: ${{ github.actor }}
          ATLANTIS_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ATLANTIS_LOCKING_DB_TYPE: redis
          ATLANTIS_REDIS_HOST: redis
          ATLANTIS_REPO_ALLOWLIST: github.com/${{ github.repository }}
        volumes:
          - /atlantis-data:/atlantis-data

    steps:
      - name: Cache Atlantis data
        id: cache-atlantis-data
        uses: actions/cache@v3
        with:
          path: /atlantis-data
          key: atlantis-data
      - name: Wait for Atlantis to start
        id: atlantis-start
        timeout-minutes: 1
        run: |
          printf 'Waiting...'
          until curl --output /dev/null --silent --fail http://localhost:4141/healthz; do
              printf '.'
              sleep 5
          done
      - name: Send event to Atlantis
        id: atlantis-event
        run: |
          curl --request POST \
            --header 'Content-Type: application/json' \
            --header 'X-GitHub-Event: ${{ github.event_name }}' \
            --header 'X-GitHub-Delivery: ${{ github.run_id }}' \
            --data '${{ toJson(github.event) }}' \
            http://localhost:4141/events
      - name: Wait for Atlantis to finish
        id: atlantis-finish
        timeout-minutes: 1
        run: |
          printf 'Waiting...'
          sleep 5
          until curl --silent http://localhost:4141/status | grep '"in_progress_operations": 0'; do
              sleep 5
          done