name: 'Atlantis'

on: pull_request

permissions:
  contents: read

jobs:
  atlantis:
    name: 'Atlantis'
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
      atlantis:
        image: ghcr.io/runatlantis/atlantis:v0.23.2
        ports:
          - 4141:4141
        env:
          ATLANTIS_GH_USER: ${{ github.triggering_actor }}
          ATLANTIS_GH_TOKEN: ${{ github.token }}
          ATLANTIS_LOG_LEVEL: debug
          ATLANTIS_LOCKING_DB_TYPE: redis
          ATLANTIS_REDIS_HOST: redis
          ATLANTIS_REPO_ALLOWLIST: 'github.com/danielgblanco/atlantis-gha-poc'

    steps:
      # Pass event to Atlantis
      - name: Send event
        run: |
          curl --request POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'X-GitHub-Event: ${{ github.event_name }}' --header 'X-GitHub-Delivery: ${{ github.run_id }}' --data '${{ toJson(github.event) }}' http://localhost:4141/events && sleep 30