name: 'Atlantis'

on: pull_request

permissions:
  contents: read

jobs:
  atlantis:
    name: 'Atlantis'
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
      atlantis:
        image: ghcr.io/runatlantis/atlantis:v0.23.2
        env:
          ATLANTIS_GH_USER: ${{ github.triggering_actor }}
          ATLANTIS_GH_TOKEN: ${{ github.token }}
          ATLANTIS_LOG_LEVEL: debug
          ATLANTIS_LOCKING_DB_TYPE: redis
          ATLANTIS_REDIS_HOST: redis
          ATLANTIS_REPO_ALLOWLIST: 'github.com/danielgblanco/atlantis-gha-poc'

    steps:
      # Pass event to Atlantis
      - name: Send event
        uses: fjogeleit/http-request-action@v1
        with:
          url: http://atlantis:4141/events
          method: POST
          customHeaders: '{"Content-Type": "application/json"}'
          data: '${{ toJson(github.event) }}'